### ISSUE TITLE
Idioma inalterado

### ISSUE THREAD

**Issue by IgorDePaula** [lucascudo/laravel-pt-BR-localization#12]
Depois de seguir o passo a passo, o idioma ficou em ingles.

Laravel 6.8, e nova 2.5.

**Comment by brunocrpontes** [comment]
Também segui o passo a passo e o idioma permanece em inglês, mas no meu caso é com o Lumen v6.0

**Comment by lucascudo** [comment]
@IgorDePaula e @brunocrpontes , receio que com Nova e Lumen as coisas sejam um pouco diferentes e vocês terão de fazer alguma adaptação para que as traduções sejam aplicadas.

Para Laravel Nova: https://nova.laravel.com/docs/3.0/customization/localization.html#relationships

Para Lumen não encontrei documentação oficial tratando do assunto, o mais próximo foi isso aqui: https://stackoverflow.com/questions/51408974/localization-in-lumen

**Comment by IgorDePaula** [comment]
@lucascudo Obrigado pela atencao
