### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by edica** [lucascudo/laravel-pt-BR-localization#16]
Na instalação com a versão Laravel 7 da isso:

Deprecation Notice: Class Lucascudo\LaravelPtBRLocalization\LaravelPtBRLocalizationServiceProvider located in ./vendor/lucascudo/laravel-pt-br-localization/src/laravel-pt-BR-localization.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.9.2/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

Aproveitando o tópico na língua portuguesa a palavra "Email" o correto é "E-mail".

Obrigado.

**Comment by andrefelipefraga** [comment]
Alguma novidade? Está quebrando minha CI na github

**Comment by lucascudo** [comment]
Corrigido pelo pull request do @Litiano .
