### ISSUE TITLE
String de verificação de email não traduzida

### ISSUE THREAD

**Issue by machadoug** [lucascudo/laravel-pt-BR-localization#19]
Ao cadastrar-se no site a string abaixo não está sendo traduzida:
`If you’re having trouble clicking the "Verificar E-mail" button, copy and paste the URL below into your web browser:`

[Segue screenshot](https://i.imgur.com/3HzhXao.png) para melhor compreensão.

Desde já agradeço.

**Comment by adrielrenato** [comment]
Gostaria de ter enviado um PR para fazer esse ajuste da tradução do e-mail, mas não consegui por não mexer muito no GitHub, mas vou colocar o ajuste aqui para ti :)

Substitua a linha 21 do arquivo pt-BR.json
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:displayableActionUrl](:actionURL)": "Se você estiver com problemas para clicar no botão \":actionText\", copie e cole o URL abaixo\nem seu navegador da web: [:displayableActionUrl](:actionURL)",

para
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Se você estiver com problemas para clicar no botão \":actionText\", copie e cole o URL abaixo\nem seu navegador da web:",

Na imagem abaixo eu mostro que dessa forma já resolve a tradução!
![image](https://user-images.githubusercontent.com/39914516/81305108-52dba380-9054-11ea-9eeb-332e80912f80.png)

**Comment by edica** [comment]
É isso mesmo adrielrenato.

Ou apenas remova: "[:displayableActionUrl](:actionURL)".

Fica assim:

"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Se você estiver com problemas para clicar no botão \":actionText\", copie e cole o URL abaixo\nem seu navegador da web:",
