### ISSUE TITLE
Nomear idioma de acordo com ISO 15897

### ISSUE THREAD

**Issue by guianzollin** [lucascudo/laravel-pt-BR-localization#20]
De acordo com a documentação do Laravel 7, você deve nomear os diretórios de idiomas de acordo com a ISO 15897. Por exemplo, "pt_BR" deve ser usado em vez de "pt-BR".

https://laravel.com/docs/7.x/localization#introduction

**Comment by lucascudo** [comment]
Obrigado. Resolvido em: https://github.com/lucascudo/laravel-pt-BR-localization/commit/cab19d539507f6950a42c12447699b761e61b20d
