### ISSUE TITLE
Sugiro adicionar as algumas chaves

### ISSUE THREAD

**Issue by albertoelias123** [lucascudo/laravel-pt-BR-localization#22]
validation.php no array 'attributes' adicionar as seguintes chaves:
- 'cell' => 'celular',
- 'neighborhood' => 'bairro',
- 'number' => 'número',
- 'street' => 'rua',
Estas são algumas chaves que eu frequentemente utilizo em minhas aplicações, acredito que seja util para outros programadores também

pt-BR.json adicionar a seguinte chave:
"Please confirm your password before continuing." : "Por favor, confirme sua senha para continuar."
Esta chave é utilizada na Tela de Confirmação de Senha do Laravel UI 2.0

Desde já agradeço pelo repositório,
Att.: Alberto E. A. Júnior.

**Comment by lucascudo** [comment]
Obrigado, @albertoelias123. Adicionado em: https://github.com/lucascudo/laravel-pt-BR-localization/commit/b1b4f6b9a7f6ea4c02087cecdcdc9a08291e97ee
