### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by danpalmieri** [lucascudo/laravel-pt-BR-localization#23]
Erro de digitação:
"Send Password Reset Link": "Enviar link para **redifinir** senha",

Correto:
"Send Password Reset Link": "Enviar Link para **Redefinir** Senha",

**Comment by lucascudo** [comment]
Obrigado. Resolvido em: https://github.com/lucascudo/laravel-pt-BR-localization/commit/19f60fa3dc7246ff20a478d79da3015a8e03c86b
