### ISSUE TITLE
rodapé com o link de ação não traduz no Laravel 6

### ISSUE THREAD

**Issue by ctodobom** [lucascudo/laravel-pt-BR-localization#26]
O rodapé ao enviar email com link, que instrui o usuário a colar o endereço no navegador, não traduz no laravel 6.x (não testei em mais recente)

**Comment by viniciushss-interstar** [comment]
Pessoal, esse problema retornou no Laravel 8, porém não consegui identificar uma possível correção. A string presente em `vendor/laravel/framework/src/Illuminate/Notifications/resources/views/email.blade.php` bate com o que está na tradução.

**Comment by viniciushss-interstar** [comment]
Encontrei o problema: eles trocaram o apóstrofo por aspas simples do "you're". Dessa forma, para ser compatível com Laravel 8, a tradução deverá incluir:

```json
"If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Se você estiver com problemas para clicar no botão \":actionText\", copie e cole o URL abaixo\nem seu navegador da web:",
```

**Comment by allgood** [comment]
Tô abrindo nova issue #44  direto para o Laravel 8 e já vou submeter o patch e o pull request #45

**Comment by allgood** [comment]
Eu ainda não sei exatamente porque, mas na minha instalação essa string não tá sendo substituída... já estava ocorrendo antes e eu acreditava que era por causa da apóstrofe não-ascii. mas continuou ocorrendo.

vou tentar debugar um pouco mais

**Comment by allgood** [comment]
Teste com o `artisan tinker` em uma instalação de laravel 8.

Nota-se que a string não é traduzida, mas outras strings são!

![image](https://user-images.githubusercontent.com/6070736/135100379-e5b20b45-417c-4874-b347-e89ccfbdf5dc.png)

**Comment by allgood** [comment]
sobre o problema acima, já determinei que é aqui do meu lado!
