### ISSUE TITLE
Correção da palavra e-mail

### ISSUE THREAD

**Issue by JoaoCapoAlm** [lucascudo/laravel-pt-BR-localization#38]
Em Português a maneira correta de se escrever é e-mail (com hífen) no arquivo [./src/pt_BR.json](https://github.com/lucascudo/laravel-pt-BR-localization/blob/master/src/pt_BR.json) possui algumas lugares que está escrito email.

**Comment by lucascudo** [comment]
https://github.com/lucascudo/laravel-pt-BR-localization/commit/acfba096d25751384bf9f6082ae9060211a3552d
