### ISSUE TITLE
Sugestão para avaliação renomear pasta

### ISSUE THREAD

**Issue by muriloelias** [lucascudo/laravel-pt-BR-localization#40]
Boa noite Lucas,

Segundo o padrão da marcação de texto lang dentro do html, BCP47, o valor para português, região brasileira deveria ser inclusa como "pt-BR" e não "pt_BR", segue fontes abaixo para avaliação.

Quem sabe mudar a pasta no script de instalação e na documentação seja uma boa.

Obrigado por disponibilizar este pacote e desconsidere se não achar relevante.

Abraço

Fonte:
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Global_attributes/lang
https://r12a.github.io/app-subtags/

**Comment by lucascudo** [comment]
https://github.com/lucascudo/laravel-pt-BR-localization/commit/6c307cc8fd1103c87657324c414e3da85119ef9f
