### ISSUE TITLE
Novo diretório lang no Laravel 9

### ISSUE THREAD

**Issue by MarceloLuis1997** [lucascudo/laravel-pt-BR-localization#50]
No laravel 9, o diretório `lang` agora fica na raiz do projeto: https://laravel.com/docs/9.x/upgrade#the-lang-directory

Ainda é possível utilizar este package, mas para seguir o novo padrão do Laravel, seria possível realizar este ajuste nas próximas versões?

**Comment by lucascudo** [comment]
Obrigado pela dica, @MarceloLuis1997. Farei a alteração indicada logo que puder.

**Comment by maciel81** [comment]
No meu script para criação do projeto eu criei um gatilho para fazer as alterações de maneira automática.

#composer require lucascudo/laravel-pt-br-localization --dev

#sed -i "s/resource_path('lang/app()->langPath('/g" vendor/lucascudo/laravel-pt-br-localization/src/LaravelPtBRLocalizationServiceProvider.php

#php artisan vendor:publish --tag=laravel-pt-br-localization

#sed -i "s/E-Mail/Email/g" lang/pt-BR.json


Obs.: Não está traduzindo corretamente a palavra email pois na chave do array em inglês é Email e não E-Mail.

**Comment by douglas-88** [comment]
> No laravel 9, o diretório `lang` agora fica na raiz do projeto: https://laravel.com/docs/9.x/upgrade#the-lang-directory
> 
> Ainda é possível utilizar este package, mas para seguir o novo padrão do Laravel, seria possível realizar este ajuste nas próximas versões?

@MarceloLuis1997 Eu consegui usar esse package no Laravel 9, não tive problemas.

**Comment by lucascudo** [comment]
Corrigido por @maciel81 em https://github.com/lucascudo/laravel-pt-BR-localization/pull/52

**Comment by begnini** [comment]
Essa correção quebrou para o laravel 8.x ou inferior. No PR eh `resource_path()` (função) e não `resource_path` (constante)

**Comment by douglas-88** [comment]
> Essa correção quebrou para o laravel 8.x ou inferior. No PR eh `resource_path()` (função) e não `resource_path` (constante)

@lucascudo @begnini 

`λ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 879:

  Target class [langPath] does not exist.


In Container.php line 877:

  Class "langPath" does not exist


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

Verdade, fui atualizar do Laravel 9.7 para o 9.8 e me apresentou este erro acima ... .

**Comment by marcelcunha** [comment]
Não sei se devo comentar aqui ou abrir uma nova issue com o mesmo assunto. Hoje, instalando o pacote numa aplicação nova Laravel 9, os arquivos foram exportados para `/resources/lang`. Tive de migrar de forma manual para `/lang`.
