### ISSUE TITLE
Undefined constant "Lucascudo\LaravelPtBRLocalization\resource_path"

### ISSUE THREAD

**Issue by alef-carvalho** [lucascudo/laravel-pt-BR-localization#53]
Após rodar um composer install o seguinte erro é gerado:

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In LaravelPtBRLocalizationServiceProvider.php line 13:

  Undefined constant "Lucascudo\LaravelPtBRLocalization\resource_path"

Informações adicionais:

- PHP 7.4
- Laravel 8.4

**Comment by lucascudo** [comment]
Fixed by @begnini  at https://github.com/lucascudo/laravel-pt-BR-localization/pull/54
