### ISSUE TITLE
Missing translation for 'max_digits' and 'min_digits' validation rules

### ISSUE THREAD

**Issue by Joelfo** [lucascudo/laravel-pt-BR-localization#63]
Both the 'min_digits' and the 'max_digits' rules are missing their translations. The result is that, when we use them, the error message in the failure cases still in English. 
'max_digits' validation rule: [https://laravel.com/docs/9.x/validation#rule-max-digits](https://laravel.com/docs/9.x/validation#rule-max-digits)
'min_digits' validation rule: [https://laravel.com/docs/9.x/validation#rule-min-digits](https://laravel.com/docs/9.x/validation#rule-min-digits)
I did a pull request fixing this issue myself, as I did for running my app. If you think that the pull request are good please merge it or fix the issue in another way. :)

**Comment by lucascudo** [comment]
Fixed on: https://github.com/lucascudo/laravel-pt-BR-localization/pull/64
