### ISSUE TITLE
Create compatibility with Lumen

### ISSUE THREAD

**Issue by luigi-raynel-dev** [lucascudo/laravel-pt-BR-localization#65]

**Comment by codespearhead** [comment]
I wonder how relevant that feature is because [Lumen's official documentation](https://lumen.laravel.com/docs/10.x#installation) says:

> Note: In the years since releasing Lumen, PHP has made a variety of wonderful performance improvements. For this reason, along with the availability of [Laravel Octane](https://laravel.com/docs/octane), we no longer recommend that you begin new projects with Lumen. Instead, we recommend always beginning new projects with [Laravel](https://laravel.com/).

By the way the last commit in their [official repository](https://github.com/laravel/lumen) seems to be over year ago.

**Comment by lucascudo** [comment]
@codespearhead made his point.
