### ISSUE TITLE
[pt-BR] Nome do diretório da conflito na tradução

### ISSUE THREAD

**Issue by Lewoaragao** [lucascudo/laravel-pt-BR-localization#77]
**Primeiramente agradeço pelo projeto**, me ajudou bastante, segundamente vim ajudar, percebi um pequeno bug ao criar a pasta de tradução para Português, como no HTML fica `pt-BR` com traço e o nome da pasta fica `pt_BR` com underline o Laravel não identificava a tradução, estou usando o **Laravel 10**, quis compartilhar só para caso mais alguém passe por esse problema e consiga resolver facilmente, segue a imagem de exemplo, somente trocar o underline da pasta por traço e ficar com o nome `pt-BR`.

![image](https://github.com/lucascudo/laravel-pt-BR-localization/assets/65857778/a488470d-8ccd-437c-8910-04aee391c34e)

**Comment by kevineduardo** [comment]
Isso porque o Laravel utiliza o padrão ISO 15897 para nomear os locais. 

PROVA: https://github.com/laravel/docs/commit/13793d42df18a39c619a7208092938189770d23f

**Comment by Lewoaragao** [comment]
Deixei o tópico pra caso alguém tenha essa dúvida que acabei tendo, obrigado ☕️

**Comment by lucascudo** [comment]
> Isso porque o Laravel utiliza o padrão ISO 15897 para nomear os locais.
> 
> PROVA: [laravel/docs@13793d4](https://github.com/laravel/docs/commit/13793d42df18a39c619a7208092938189770d23f)

Pelo que entendi, devemos voltar a utilizat "pt_BR" como nome do diretório, correto?
