### ISSUE TITLE
bug: erro no arquivo pt-BR.json

### ISSUE THREAD

**Issue by maykonaraujo** [lucascudo/laravel-pt-BR-localization#80]
Eu fiz o passo a passo da implantação da biblioteca no meu projeto. Entretanto, ao rodar o código, apareceu este erro:
`{
    "message": "Translation file [/var/www/html/lang/pt-BR.json] contains an invalid JSON structure.",
    "exception": "RuntimeException",
    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php",
    "line": 152
}`

Então, eu fui lá no arquivo pt-BR.json que está dentro da lang\pt-BR.json e removi uma vírgula que tem no final do arquivo.

`  "Remove": "Remover",
}`
<img width="538" alt="image" src="https://github.com/lucascudo/laravel-pt-BR-localization/assets/6663881/6ff31a21-b181-47cd-8def-24481898918f">

Assim, a tradução funcionou.

**Comment by lucascudo** [comment]
Thank's for noticing. Fixing at v2.1.2
