### ISSUE TITLE
Erro ao executar php artisan lang:publish

### ISSUE THREAD

**Issue by Rodrigolmod** [lucascudo/laravel-pt-BR-localization#81]
Quando eu executo o comando php `artisan lang:publish` é retornado o erro  " There are no commands defined in the "lang" namespace. "

**Comment by lucascudo** [comment]
Olá @Rodrigolmod, tudo bem? Este comando é do Laravel e não do pacote de traduções: https://laravel.com/docs/11.x/localization#publishing-the-language-files
Caso não tenha resolvido o problema, vc precisa pedir suporte no projeto do Laravel, blz?
