### ISSUE TITLE
There are no commands defined in the "lang" namespace.

### ISSUE THREAD

**Issue by Rodrigolmod** [lucascudo/laravel-pt-BR-localization#82]
Logo no primeiro comando, aparece esse erro ai:

There are no commands defined in the "lang" namespace.

**Comment by lucascudo** [comment]
Como já informei em sua outra Pull request, você tem de buscar o suporte do laravel: https://github.com/lucascudo/laravel-pt-BR-localization/issues/81

**Comment by Rodrigolmod** [comment]
Opa, eu não tinha visto que tinha fechado e me respondido, desculpe.

Cara, eu vi na internet que esse primeiro comando é só para versões posteriores do Laravel que estou usando (estou usando Laravel 8), etnão eu executei o seu tutorial do passo 2 em diante e deu certo.

Obrigado pela atenção e desculpe novamente pela falta de atenção da minha parte, sou iniciante.
