### ISSUE TITLE
ISO 15897 é o padrão utilizado pelo Laravel

### ISSUE THREAD

**Issue by kevineduardo** [lucascudo/laravel-pt-BR-localization#85]
Estou reabrindo essa issue, pois o projeto voltou a não seguir a documentação.

Prova: https://github.com/laravel/docs/commit/13793d42df18a39c619a7208092938189770d23f

**Comment by lucascudo** [comment]
Pelo que entendi, devemos voltar a utilizat "pt_BR" como nome do diretório, correto?
