### ISSUE TITLE
Não funcionou

### ISSUE THREAD

**Issue by Errcr404** [lucascudo/laravel-pt-BR-localization#98]
C:\laragon\www\v159
λ composer require lucascudo/laravel-pt-br-localization --dev
Using version ^2.2 for lucascudo/laravel-pt-br-localization
./composer.json has been updated
Running composer update lucascudo/laravel-pt-br-localization
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking lucascudo/laravel-pt-br-localization (v2.2.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading lucascudo/laravel-pt-br-localization (v2.2.5)
  - Installing lucascudo/laravel-pt-br-localization (v2.2.5): Extracting archive
Generating optimized autoload files

Class App\Http\Controllers\Admin\CommonController located in C:/laragon/www/v159/app\Http\Controllers\CommonController.php does not comply with psr-4 autoloading standard. Skipping.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.

  laravel/breeze ................................................................................................ DONE
  laravel/sail .................................................................................................. DONE
  laravel/sanctum ............................................................................................... DONE
  laravel/tinker ................................................................................................ DONE
  lucascudo/laravel-pt-br-localization .......................................................................... DONE
  mews/captcha .................................................................................................. DONE
  nesbot/carbon ................................................................................................. DONE
  nunomaduro/collision .......................................................................................... DONE
  nunomaduro/termwind ........................................................................................... DONE
  pestphp/pest .................................................................................................. DONE
  spatie/laravel-ignition ....................................................................................... DONE

90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].

No security vulnerability advisories found

C:\laragon\www\v159
λ php artisan vendor:publish --tag=laravel-pt-br-localization

   INFO  Publishing [laravel-pt-br-localization] assets.

  Copying file [C:\laragon\www\v159\vendor\lucascudo\laravel-pt-br-localization\src\pt_BR.json] to [C:\laragon\www\v159\lang\pt_BR.json]  DONE
  Copying directory [C:\laragon\www\v159\vendor\lucascudo\laravel-pt-br-localization\src\pt_BR] to [C:\laragon\www\v159\lang\pt_BR]  DONE
  
  Renominei de en para pt_BR no app.php, mas não fuincionou =/ meu site ainda continua em ingles

**Comment by lucascudo** [comment]
Você pode mover o arquivo para app/Http/Controllers/Admin/CommonController.php ou alterar o namespace no arquivo CommonController.php para App\Http\Controllers.

Execute composer dump-autoload após fazer essas alterações.

Resposta completa do chatgpt: https://chatgpt.com/share/6718c583-86fc-8007-b3dc-3a3c54f9f01f
